### ISSUE TITLE
RUNBOT credentials 

### ISSUE THREAD

**Issue by Protoneer** [OCA/knowledge#280]
trying to evaluate these modules but I can't log into the runbot website.

Tried...
user : admin 
pw: admin 

but it says its the wrong password

**Comment by pedrobaeza** [comment]
Runbot is not working right now and it's redirected to the main instance, so you are trying to login on runbot Odoo.

cc @gurneyalex @sbidoul

**Comment by gurneyalex** [comment]
The issue should be solved now (a certificate renewal changed a path which caused nginx to not restart on runbot2, breaking the connections running on that server).

**Comment by Protoneer** [comment]
Still not working.... 

Saying the password is wrong.

Can we confirm that the credentials are:
user : admin
pw: admin

(Using Chrome I cleared my browser cache)
